version: 2
jobs:
  wakeTestServers:
    docker:
      - image: circleci/node:12.6.0-browsers
    steps:
      - run:
          name: Ping arms test server
          command: curl --silent https://test-armadillo-arms.herokuapp.com/
      - run:
          name: Ping legs test server
          command: curl --silent https://test-armadillo-legs.herokuapp.com/
  unitTest:
    docker:
      - image: circleci/node:12.6.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run eslint
          command: npm run lint
      - run:
          name: Run unit tests and check coverage
          command: npm run test:cov
  build:
    docker:
      - image: circleci/node:12.6.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: run the build
          command: npm run build
  resetTestDb:
    docker:
      - image: circleci/mongo:3.6.12
    steps:
      - run:
          name: Drop test database
          command: mongo $HEROKU_TEST_DB -u $HEROKU_TEST_DB_USER -p $HEROKU_TEST_DB_PASSWORD --eval "db.dropDatabase()"
      - run:
          name: Insert superAdmin in test database
          command: mongo $HEROKU_TEST_DB -u $HEROKU_TEST_DB_USER -p $HEROKU_TEST_DB_PASSWORD --eval "db.users.insertOne({email:'baqa@thoughtworks.com',password:'\$2a\$10\$IGceut2T1G1A8/celqCEFOJw4a2Gen1ljz0fKwPtBJL/OHc75ORlu',role:'admin'})"
  uiTest:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Verify Cypress
          command: npm run cy:verify
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run Cypress E2E tests
          command: npm run cy:run
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  deployTest:
    docker:
      - image: circleci/node:12.6.0
    environment:
      HEROKU_APP_NAME: test-armadillo-arms
    steps:
      - checkout
      - run:
          name: Deploy to test frontend on Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run:
          name: Check test deployment
          command: curl --fail https://$HEROKU_APP_NAME.herokuapp.com/
  deployDemo:
    docker:
      - image: circleci/node:12.6.0
    environment:
      HEROKU_APP_NAME: demo-armadillo-arms
    steps:
      - checkout
      - run:
          name: Deploy to demo frontend on Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run:
          name: Check demo deployment
          command: curl --fail https://$HEROKU_APP_NAME.herokuapp.com/
  deployProd:
    docker:
      - image: circleci/node:12.6.0
    environment:
      HEROKU_APP_NAME: armadillo-arms
    steps:
      - checkout
      - run:
          name: Deploy to production frontend on Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run:
          name: Check production deployment
          command: curl --fail https://$HEROKU_APP_NAME.herokuapp.com/
workflows:
  version: 2
  BuildTestDeploy:
    jobs:
      - wakeTestServers
      - unitTest
      - build:
          requires:
            - unitTest
      - deployTest:
          requires:
            - build
            - wakeTestServers
      - resetTestDb:
          requires:
            - wakeTestServers
      - uiTest:
          requires:
            - resetTestDb
            - deployTest
      - deployDemo:
          type: approval
          requires:
            - uiTest
      - deployProd:
          type: approval
          requires:
            - deployDemo
